A smidge more tweaking of the smoke test site stuff

diff --git a/examples/smoke-test-site/smoke-suite b/examples/smoke-test-site/smoke-suite
--- a/examples/smoke-test-site/smoke-suite
+++ b/examples/smoke-test-site/smoke-suite
@@ -9,25 +9,23 @@ fi
 SERVER_PID=""
 URL_BASE="http://localhost:9182"
 
-export GOASPEN_CONFIGURATION_SCRIPTS="$HERE/web-config.go"
-export DEBUG=1
-export GOPATH="$HERE:$GOPATH"
-
 function curl_check200() {
-    echo -n "$1 "
-    curl -s -i "$URL_BASE${1}" | head -1 | awk '{ print $2 }' | grep 200
+    local status
+    status="$(curl -s -i "$URL_BASE${1}" | head -1 | awk '{ print $2 }')"
+    echo "$1 -> $status"
+    echo $status | grep 200 >/dev/null
 }
 
-trap "test -n \"$SERVER_PID\" && kill -9 $SERVER_PID" 1 2 3 15
+function die() {
+    set +e
+    set +o pipefail
+    test -n "$SERVER_PID" && kill -9 $SERVER_PID
+    echo -e "\033[1;31m-------- FAILURE --------\033[0m"
+}
 
-goaspen-build \
-    -w "$HERE/docroot" \
-    -P goaspen_smoke_test \
-    --indices +default.htm \
-    --list_directories \
-    -x \
-    -s \
-    --changes_reload >>$HERE/smoke-server.log 2>&1 &
+trap 'die' 1 2 3 15
+
+$HERE/build -x -s --changes_reload >>$HERE/smoke-server.log 2>&1 &
 
 SERVER_PID="$!"
 
@@ -61,3 +59,5 @@ kill -INT "$SERVER_PID"
 killall -s INT goaspen_smoke_test-http-server
 sleep 5
 SERVER_PID=""
+
+echo -e "\033[1;32m-------- SUCCESS --------\033[0m"
